fix(Dockerfile): fix docker deployment
Previous Go version caused `
ERROR: failed to solve: process "/bin/sh -c go run ./server/ -build-frontend   && go build -o edna ./server/" did not complete successfully: exit code: 1`